apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
  - ../../base
  - namespace.yaml
  - dragonfly.yaml
  - hpa.yaml

patches:
  - path: patches/deployment-patch.yaml
  - path: patches/resources-patch.yaml